
services:
  mongo:
    image: mongo:6
    container_name: easypadel-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easypadel-api
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    # Volumes pour le DEV (Ã  commenter en PROD)
    # volumes:
    #   - "${PWD}/backend:/app"
    #   - /app/node_modules
    command: npm start 
    restart: unless-stopped

volumes:
  mongo_data: {}
